name: "📌 Task Kick-off mil 1.1"
description: Task thuộc milestone 1.1 – Setup và phân công
labels: [documentation, priority: high]
body:
  - type: input
    id: task_title
    attributes:
      label: Tên task
      placeholder: "Việc cần thực hiện"

  - type: textarea
    id: task_details
    attributes:
      label: Nội dung công việc
      placeholder: |
        - Add all members vào GitHub Org
        - Tạo GitHub Project
        - Mời giảng viên vào Org
