name: "🧩 Task Design & Docs mil 1.2"
description: Task thuộc milestone 1.2 – Thiết kế và tài liệu game
labels: [documentation, 1.2]
body:
  - type: input
    id: task_title
    attributes:
      label: Tên task
      placeholder: "Việc cần thực hiện"

  - type: textarea
    id: task_details
    attributes:
      label: Nội dung công việc
      placeholder: |
        - Viết mô tả chức năng từng màn hình
        - Phân tích các hàm chính: renderBoard, handleClick...
        - Chia phần mô tả trên Overleaf
