name: "🧪 Task Dev Sprint 2 – mil 1.4"
description: Task thuộc milestone 1.4 – Dev Sprint 2 + Test
labels: [development, testing, 1.4]
body:
  - type: input
    id: task_title
    attributes:
      label: Tên task
      placeholder: "Popup win/loss, chức năng nâng cao..."

  - type: textarea
    id: task_details
    attributes:
      label: Mô tả công việc
      placeholder: |
        - Cài đặt popup thông báo kết quả
        - Thêm animation khi thắng
        - Test multi-device
