name: "🧾 Task Wrap-up & Nộp báo cáo – mil 1.5"
description: Task thuộc milestone 1.5 – Tổng kết & nộp file
labels: [report, 1.5]
body:
  - type: input
    id: task_title
    attributes:
      label: Tên task
      placeholder: "Xuất PDF, kiểm tra format..."

  - type: textarea
    id: task_details
    attributes:
      label: Nội dung công việc
      placeholder: |
        - Finalize file trên Overleaf
        - Xuất báo cáo đúng định dạng
        - Upload video demo lên Drive
