name: "🐞 Bug Report"
description: Báo cáo lỗi trong hệ thống
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Mô tả lỗi
      placeholder: "Khi bấm nút reset thì trò chơi không khởi động lại..."

  - type: textarea
    id: steps
    attributes:
      label: Các bước tái hiện lỗi (không bắt buộc)
      placeholder: |
        1. Mở trang Game
        2. Click nút Reset
        3. Không có gì xảy ra

  - type: dropdown
    id: severity
    attributes:
      label: Mức độ nghiêm trọng
      options:
        - Thấp
        - Trung bình
        - Cao
