name: "🌟 Feature Request"
description: Gợi ý hoặc yêu cầu chức năng mới
labels: [enhancement]
body:
  - type: input
    id: feature_title
    attributes:
      label: Tính năng cần thêm
      placeholder: "Undo nước đi cuối cùng"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Bối cảnh / Lý do (tuỳ chọn)
      placeholder: "Thường hay bấm nhầm, cần undo để tránh sai"
