name: "📌 Task Kick-off mil 1.1"
description: Task thuộc milestone 1.1 - Setup và phân công
title: "[1.1][DOCS] | "
body:
  - type: input
    id: task_title
    attributes:
      label: Tên task
      placeholder: "Việc cần thực hiện"
    validations:
      required: true

  - type: textarea
    id: task_details
    attributes:
      label: Nội dung công việc
      placeholder: |
        - Add all members vào GitHub Org
        - Tạo GitHub Project
        - Invite giảng viên vào Org
