name: Code Quality Check

on:
  push:
    branches:
      - main # Chỉ chạy khi push trực tiếp vào main
  pull_request:
    branches:
      - "**" # Chạy khi mở hoặc cập nhật PR vào bất kỳ nhánh nào

jobs:
  check-code:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài codespell để kiểm tra chính tả
      - name: Install codespell
        run: pip install codespell

      # Bước 3: Kiểm tra chính tả (bỏ qua các từ trong .codespell-ignore)
      - name: Run codespell
        run: codespell --ignore-words=.codespell-ignore --skip="*.min.js,*.min.css,*.png,*.jpg,*.gif,*.woff,*.ttf" .
